// Code generated by "shoot new -getset -file=base.go"; DO NOT EDIT. (v0.7.1)

package entity

// NewBase[Tid ID] constructs a new instance of type Base[Tid]
func NewBase[Tid ID](id Tid) *Base[Tid] {
	return &Base[Tid]{
		id: id,
	}
}

// Id gets the value of field id
func (b *Base[Tid]) Id() Tid {
	return b.id
}

// BaseGetter[Tid ID] is read-only interface for Base[Tid] type
type BaseGetter[Tid ID] interface {
	Id() Tid
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (b Base[Tid]) ShootNew() { /*noop*/ }
