// Code generated by "shoot new -getset -file=user.go"; DO NOT EDIT. (v0.7.1)

package entity

import (
	"time"

	"github.com/lopolopen/t-fiber-kafka-gorm/internal/domain/enum"
)

// NewUser constructs a new instance of type User
func NewUser(id uint, name string, birthday time.Time, gender enum.Gender) *User {
	return &User{
		Base: Base[uint]{
			id: id,
		},
		name:     name,
		birthday: birthday,
		gender:   gender,
	}
}

// Name gets the value of field name
func (u *User) Name() string {
	return u.name
}

// Birthday gets the value of field birthday
func (u *User) Birthday() time.Time {
	return u.birthday
}

// Gender gets the value of field gender
func (u *User) Gender() enum.Gender {
	return u.gender
}

// SetName sets the value of field name
func (u *User) SetName(name_ string) {
	u.name = name_
}

// SetBirthday sets the value of field birthday
func (u *User) SetBirthday(birthday_ time.Time) {
	u.birthday = birthday_
}

// SetGender sets the value of field gender
func (u *User) SetGender(gender_ enum.Gender) {
	u.gender = gender_
}

// UserGetter is read-only interface for User type
type UserGetter interface {
	BaseGetter[uint]
	Name() string
	Birthday() time.Time
	Gender() enum.Gender
}

// UserSetter is write-only interface for User type
type UserSetter interface {
	SetName(string)
	SetBirthday(time.Time)
	SetGender(enum.Gender)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (u User) ShootNew() { /*noop*/ }
