// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/schema/error_reason.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_UNSPECIFIED             ErrorReason = 0
	ErrorReason_INVALID_IDEMPOTENCY_KEY ErrorReason = 401
	ErrorReason_INVALID_REQUEST_FIELDS  ErrorReason = 402
	ErrorReason_NIL_ARGUMENT            ErrorReason = 501
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:   "UNSPECIFIED",
		401: "INVALID_IDEMPOTENCY_KEY",
		402: "INVALID_REQUEST_FIELDS",
		501: "NIL_ARGUMENT",
	}
	ErrorReason_value = map[string]int32{
		"UNSPECIFIED":             0,
		"INVALID_IDEMPOTENCY_KEY": 401,
		"INVALID_REQUEST_FIELDS":  402,
		"NIL_ARGUMENT":            501,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_schema_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_pkg_schema_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_pkg_schema_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_pkg_schema_error_reason_proto protoreflect.FileDescriptor

const file_pkg_schema_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/schema/error_reason.proto\x12\x06schema*l\n" +
	"\vErrorReason\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x17INVALID_IDEMPOTENCY_KEY\x10\x91\x03\x12\x1b\n" +
	"\x16INVALID_REQUEST_FIELDS\x10\x92\x03\x12\x11\n" +
	"\fNIL_ARGUMENT\x10\xf5\x03B;Z9github.com/lopolopen/t-fiber-kafka-gorm/pkg/schema;schemab\x06proto3"

var (
	file_pkg_schema_error_reason_proto_rawDescOnce sync.Once
	file_pkg_schema_error_reason_proto_rawDescData []byte
)

func file_pkg_schema_error_reason_proto_rawDescGZIP() []byte {
	file_pkg_schema_error_reason_proto_rawDescOnce.Do(func() {
		file_pkg_schema_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_schema_error_reason_proto_rawDesc), len(file_pkg_schema_error_reason_proto_rawDesc)))
	})
	return file_pkg_schema_error_reason_proto_rawDescData
}

var file_pkg_schema_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_schema_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: schema.ErrorReason
}
var file_pkg_schema_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_schema_error_reason_proto_init() }
func file_pkg_schema_error_reason_proto_init() {
	if File_pkg_schema_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_schema_error_reason_proto_rawDesc), len(file_pkg_schema_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_schema_error_reason_proto_goTypes,
		DependencyIndexes: file_pkg_schema_error_reason_proto_depIdxs,
		EnumInfos:         file_pkg_schema_error_reason_proto_enumTypes,
	}.Build()
	File_pkg_schema_error_reason_proto = out.File
	file_pkg_schema_error_reason_proto_goTypes = nil
	file_pkg_schema_error_reason_proto_depIdxs = nil
}
