env: prod
port: 8080
bind:
swagger:
  host: localhost:8080
  basePath: /
logger:
  level: warn
  json: true
orm:
  logLevel: off
  mysql:
    dsn: <usr>:<password>@tcp(127.0.0.1:3306)/<db>?charset=utf8mb4&parseTime=True&loc=Local
    maxIdleConns: 20
    maxOpenConns: 200
kafka:
  brokers: 
    - 127.0.0.1:9092
  username:
  password:
