bind: 0.0.0.0
timeout: 0
logger:
  level: debug
  json: false
orm:
  auto_migrate: false
  log_level: debug
  mysql:
    dsn: root:root@tcp(mariadb:3306)/debug?charset=utf8mb4&parseTime=True&loc=Local
kafka:
  brokers:
    - kafka:9092
