// Code generated by "shoot map -path=../../../domain/entity -file=user.go"; DO NOT EDIT. (v0.7.1)

package po

import "github.com/lopolopen/t-fiber-kafka-gorm/internal/domain/entity"

// ToEntity converts receiver to type entity.User
func (u *User) ToEntity() *entity.User {
	if u == nil {
		return nil
	}
	user_ := entity.NewUser(
		u.ID,       //Base.id
		u.Name,     //name
		u.Birthday, //birthday
		u.Gender,   //gender
	)
	return user_
}

// FromEntity reads from type entity.User, then writes back to receiver and returns it
func (u *User) FromEntity(user_ *entity.User) *User {
	if user_ == nil {
		return nil
	}
	if u == nil {
		u = new(User)
	} else {
		*u = User{}
	}
	u.Birthday = user_.Birthday()
	u.Gender = user_.Gender()
	u.ID = user_.Id()
	u.Name = user_.Name()
	u.readEntity(user_)
	return u
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (u User) ShootMap() { /*noop*/ }
