basePath: /
definitions:
  dto.Resp-any:
    properties:
      data: {}
      message:
        type: string
      reason:
        type: string
    type: object
  dto.Resp-array_result_User:
    properties:
      data:
        items:
          $ref: '#/definitions/result.User'
        type: array
      message:
        type: string
      reason:
        type: string
    type: object
  result.User:
    properties:
      age:
        type: integer
      birthday:
        example: "1987-11-29"
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: user@example.com
    name: Owner
  description: This is the <app-name> API documentation.
  title: <app-name> API
  version: "1.0"
paths:
  /api/v1/users:
    get:
      description: Query users by key.
      parameters:
      - description: Search key for User name
        in: query
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Resp-any'
      summary: Query users.
      tags:
      - User
swagger: "2.0"
