// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/gofiber/fiber/v2"
	"github.com/lopolopen/t-fiber-kafka-gorm/cmd/api/config"
	"github.com/lopolopen/t-fiber-kafka-gorm/internal/adapters/http"
	"github.com/lopolopen/t-fiber-kafka-gorm/internal/applic/service"
	"github.com/lopolopen/t-fiber-kafka-gorm/internal/infra/conf"
	"github.com/lopolopen/t-fiber-kafka-gorm/internal/infra/gorm"
	"github.com/lopolopen/t-fiber-kafka-gorm/internal/infra/gorm/repoimpl"
	"log/slog"
)

import (
	_ "github.com/lopolopen/t-fiber-kafka-gorm/cmd/api/docs"
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(ctx context.Context, c *config.Config, orm conf.ORM, log *slog.Logger) (*fiber.App, error) {
	db := gorm.NewGormDB(orm)
	v := http.NewPub(ctx, c, db, log)
	userRepo := repoimpl.NewUserRepo(db)
	userSvc := service.NewUserSvc(db, v, userRepo)
	app := http.NewApp(userSvc, v)
	return app, nil
}
