// Code generated by "shoot enum -json -text -sql -gorm -file=enums.go"; DO NOT EDIT. (v0.7.1)

package enum

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/lopolopen/shoot"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

func _() {
	var x [1]struct{}
	_ = x[GenderUnknown-0]
	_ = x[GenderMale-1]
	_ = x[GenderFemale-2]
}

const _gender_max = GenderUnknown | GenderMale | GenderFemale

var _gender_values = []Gender{GenderUnknown, GenderMale, GenderFemale}

var _gender_strings = []string{"Unknown", "Male", "Female"}

var _gender_string_map = map[Gender]string{
	GenderUnknown: "Unknown",
	GenderMale:    "Male",
	GenderFemale:  "Female",
}

var _gender_value_map = map[string]Gender{
	"Unknown": GenderUnknown,
	"Male":    GenderMale,
	"Female":  GenderFemale,
}

// String returns the string value of type Gender
func (g Gender) String() string {
	str, ok := _gender_string_map[g]
	if ok {
		return str
	}
	if g < 0 || g > _gender_max {
		return fmt.Sprintf("%d", g)
	}

	return fmt.Sprintf("%d", g)
}

func (g Gender) Values() []Gender {
	return _gender_values
}

func (g Gender) Strings() []string {
	return _gender_strings
}

func (g Gender) IsValid() bool {
	_, ok := _gender_string_map[g]
	return ok
}

func (g Gender) ValueMap() map[string]Gender {
	return _gender_value_map
}

func (g Gender) StringMap() map[Gender]string {
	return _gender_string_map
}

// MarshalJSON implements the json.Marshaler interface for Gender
func (g Gender) MarshalJSON() ([]byte, error) {
	return json.Marshal(g.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Gender
func (g *Gender) UnmarshalJSON(data []byte) error {
	var s_ string
	var v_ Gender
	var err error
	if err = json.Unmarshal(data, &s_); err != nil {
		return fmt.Errorf("Gender enum should be a string, got %s", data)
	}
	if v_, err = shoot.ParseEnum[Gender](s_); err != nil {
		return err
	}
	*g = v_
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for Gender
func (g Gender) MarshalText() ([]byte, error) {
	return []byte(g.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Gender
func (g *Gender) UnmarshalText(text []byte) error {
	var v_ Gender
	var err error
	if v_, err = shoot.ParseEnum[Gender](string(text)); err != nil {
		return err
	}
	*g = v_
	return nil
}

// Value implements the driver.Valuer interface for Gender
func (g Gender) Value() (driver.Value, error) {
	return g.String(), nil
}

// Scan implements the driver.Scanner interface for Gender
func (g *Gender) Scan(value interface{}) error {
	data, ok := value.([]byte)
	if !ok {
		return errors.New("bad enum type")
	}
	e_, err := shoot.ParseEnum[Gender](string(data))
	if err != nil {
		return err
	}
	*g = e_
	return nil
}

// GormDataType specifies the general data type that GORM should treat this field as.
func (g Gender) GormDataType() string {
	return "string"
}

// GormDBDataType provides the exact database column type definition for this field.
func (g Gender) GormDBDataType(db *gorm.DB, field *schema.Field) string {
	return "ENUM('Unknown','Male','Female')"
}

// ShootEnum exists solely to fulfill the EnumShooter interface contract
func (g Gender) ShootEnum() { /*noop*/ }
