// Code generated by "shoot new -json -file=flash.go"; DO NOT EDIT. (v0.7.1)

package cmd

import "encoding/json"

// NewFlashTryCmd constructs a new instance of type FlashTryCmd
func NewFlashTryCmd(so string, productId uint) *FlashTryCmd {
	return &FlashTryCmd{
		SO:        so,
		ProductID: productId,
	}
}

type _json_FlashTryCmd struct {
	SO        string `json:"so"`
	ProductID uint   `json:"productId"`
}

// MarshalJSON serializes type FlashTryCmd to json bytes
func (f FlashTryCmd) MarshalJSON() ([]byte, error) {
	data := _json_FlashTryCmd{
		SO:        f.SO,
		ProductID: f.ProductID,
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type FlashTryCmd
func (f *FlashTryCmd) UnmarshalJSON(data []byte) error {
	var flashTryCmd_ _json_FlashTryCmd
	if err := json.Unmarshal(data, &flashTryCmd_); err != nil {
		return err
	}
	f.SO = flashTryCmd_.SO
	f.ProductID = flashTryCmd_.ProductID
	return nil
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (f FlashTryCmd) ShootNew() { /*noop*/ }
