// Code generated by "shoot new -json -file=greetcmd.go"; DO NOT EDIT. (v0.7.1)

package cmd

import "encoding/json"

// NewGreetCmd constructs a new instance of type GreetCmd
func NewGreetCmd(name string) *GreetCmd {
	return &GreetCmd{
		Name: name,
	}
}

type _json_GreetCmd struct {
	Name string `json:"name"`
}

// MarshalJSON serializes type GreetCmd to json bytes
func (g GreetCmd) MarshalJSON() ([]byte, error) {
	data := _json_GreetCmd{
		Name: g.Name,
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type GreetCmd
func (g *GreetCmd) UnmarshalJSON(data []byte) error {
	var greetCmd_ _json_GreetCmd
	if err := json.Unmarshal(data, &greetCmd_); err != nil {
		return err
	}
	g.Name = greetCmd_.Name
	return nil
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (g GreetCmd) ShootNew() { /*noop*/ }
