// Code generated by "shoot new -json -file=greet.go"; DO NOT EDIT. (v0.7.1)

package cmd

import "encoding/json"

// NewGreet constructs a new instance of type Greet
func NewGreet(name string) *Greet {
	return &Greet{
		Name: name,
	}
}

type _json_Greet struct {
	Name string `json:"name"`
}

// MarshalJSON serializes type Greet to json bytes
func (g Greet) MarshalJSON() ([]byte, error) {
	data := _json_Greet{
		Name: g.Name,
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type Greet
func (g *Greet) UnmarshalJSON(data []byte) error {
	var greet_ _json_Greet
	if err := json.Unmarshal(data, &greet_); err != nil {
		return err
	}
	g.Name = greet_.Name
	return nil
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (g Greet) ShootNew() { /*noop*/ }
