// Code generated by "shoot new -json -file=quant.go"; DO NOT EDIT. (v0.7.1)

package cmd

import "encoding/json"

// NewDemand constructs a new instance of type Demand
func NewDemand(productId uint, qty int) *Demand {
	return &Demand{
		ProductID: productId,
		Qty:       qty,
	}
}

type _json_Demand struct {
	ProductID uint `json:"productId"`
	Qty       int  `json:"qty"`
}

// MarshalJSON serializes type Demand to json bytes
func (d Demand) MarshalJSON() ([]byte, error) {
	data := _json_Demand{
		ProductID: d.ProductID,
		Qty:       d.Qty,
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type Demand
func (d *Demand) UnmarshalJSON(data []byte) error {
	var demand_ _json_Demand
	if err := json.Unmarshal(data, &demand_); err != nil {
		return err
	}
	d.ProductID = demand_.ProductID
	d.Qty = demand_.Qty
	return nil
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (d Demand) ShootNew() { /*noop*/ }

// NewTryReserveCmd constructs a new instance of type TryReserveCmd
func NewTryReserveCmd(origin string, demands []Demand, remarks string) *TryReserveCmd {
	return &TryReserveCmd{
		Origin:  origin,
		Demands: demands,
		Remarks: remarks,
	}
}

type _json_TryReserveCmd struct {
	Origin  string   `json:"origin"`
	Demands []Demand `json:"demands"`
	Remarks string   `json:"remarks"`
}

// MarshalJSON serializes type TryReserveCmd to json bytes
func (t TryReserveCmd) MarshalJSON() ([]byte, error) {
	data := _json_TryReserveCmd{
		Origin:  t.Origin,
		Demands: t.Demands,
		Remarks: t.Remarks,
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type TryReserveCmd
func (t *TryReserveCmd) UnmarshalJSON(data []byte) error {
	var tryReserveCmd_ _json_TryReserveCmd
	if err := json.Unmarshal(data, &tryReserveCmd_); err != nil {
		return err
	}
	t.Origin = tryReserveCmd_.Origin
	t.Demands = tryReserveCmd_.Demands
	t.Remarks = tryReserveCmd_.Remarks
	return nil
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (t TryReserveCmd) ShootNew() { /*noop*/ }

// NewCommitCmd constructs a new instance of type CommitCmd
func NewCommitCmd(origin string) *CommitCmd {
	return &CommitCmd{
		Origin: origin,
	}
}

type _json_CommitCmd struct {
	Origin string `json:"origin"`
}

// MarshalJSON serializes type CommitCmd to json bytes
func (c CommitCmd) MarshalJSON() ([]byte, error) {
	data := _json_CommitCmd{
		Origin: c.Origin,
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type CommitCmd
func (c *CommitCmd) UnmarshalJSON(data []byte) error {
	var commitCmd_ _json_CommitCmd
	if err := json.Unmarshal(data, &commitCmd_); err != nil {
		return err
	}
	c.Origin = commitCmd_.Origin
	return nil
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (c CommitCmd) ShootNew() { /*noop*/ }

// NewReleaseCmd constructs a new instance of type ReleaseCmd
func NewReleaseCmd(origin string) *ReleaseCmd {
	return &ReleaseCmd{
		Origin: origin,
	}
}

type _json_ReleaseCmd struct {
	Origin string `json:"origin"`
}

// MarshalJSON serializes type ReleaseCmd to json bytes
func (r ReleaseCmd) MarshalJSON() ([]byte, error) {
	data := _json_ReleaseCmd{
		Origin: r.Origin,
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type ReleaseCmd
func (r *ReleaseCmd) UnmarshalJSON(data []byte) error {
	var releaseCmd_ _json_ReleaseCmd
	if err := json.Unmarshal(data, &releaseCmd_); err != nil {
		return err
	}
	r.Origin = releaseCmd_.Origin
	return nil
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (r ReleaseCmd) ShootNew() { /*noop*/ }
