// Code generated by "gapc -file=usersvc.go"; DO NOT EDIT.

package service

import (
	"context"
	"encoding/json"

	"github.com/lopolopen/gap"
	"github.com/lopolopen/gap/gapc"
	"github.com/lopolopen/t-fiber-kafka-gorm/internal/domain/event"
)

func init() {
	var _svc *UserSvc
	gap.Subscribe(
		gapc.GoGenerated(),
		gapc.Resolve(
			gapc.FuncName("service.HandlerUserCreated"),
			gapc.ResolveType("*UserSvc", func(v *UserSvc) { _svc = v }),
		),
		gapc.HandleTopicWithinGroupRaw(
			func(ctx context.Context, data_ []byte, headers_ map[string]string) error {
				var msg_ *event.UserCreated
				err := json.Unmarshal(data_, &msg_)
				if err != nil {
					return err
				}
				handler := _svc.HandlerUserCreated()
				err = handler(ctx, msg_, headers_)
				if err != nil {
					return err
				}
				return nil
			},
			new(event.UserCreated).Topic(),
			"github.com.lopolopen.t-fiber-kafka-gorm",
		),
	)
}
